In [1]:
import os

cwd = os.getcwd()  # Get the current working directory (cwd)
files = os.listdir(cwd)  # Get all the files in that directory
print("Files in %r: %s" % (cwd, files))

Files in '/Users/rupinderkohli/workspace/Python': ['streamlit', '.DS_Store', 'eda_penguins', 'rupinderk', 'node_modules', 'Rupinder_March 2020 Cohort_Term5_Grocery_Supplies_v6_Apriori.ipynb', 'rupinderk.pub', '.idea']


In [8]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from IPython.display import display



In [3]:
# how to fix Python SSL errors when downloading web pages using the https protocol in Python (e.g. by using the urllib, urllib2, httplib or requests. This error looks like something like this
# self._sslobj.do_handshake()
#   SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context

In [4]:
penguins_adelie_df = pd.read_csv("https://raw.githubusercontent.com/rupkohli/penguins/main/raw_data/penguin_chinstrap_table_221.csv")
penguins_adelie_df.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   studyName            68 non-null     object 
 1   Sample Number        68 non-null     int64  
 2   Species              68 non-null     object 
 3   Region               68 non-null     object 
 4   Island               68 non-null     object 
 5   Stage                68 non-null     object 
 6   Individual ID        68 non-null     object 
 7   Clutch Completion    68 non-null     object 
 8   Date Egg             68 non-null     object 
 9   Culmen Length (mm)   68 non-null     float64
 10  Culmen Depth (mm)    68 non-null     float64
 11  Flipper Length (mm)  68 non-null     int64  
 12  Body Mass (g)        68 non-null     int64  
 13  Sex                  68 non-null     object 
 14  Delta 15 N (o/oo)    67 non-null     float64
 15  Delta 13 C (o/oo)    68 non-null     float

In [5]:
penguins_chinstrap_df = pd.read_csv("https://raw.githubusercontent.com/rupkohli/penguins/main/raw_data/penguin_chinstrap_table_221.csv")
penguins_chinstrap_df.head()

studyName  Sample Number                                    Species  Region  \
0   PAL0708              1  Chinstrap penguin (Pygoscelis antarctica)  Anvers   
1   PAL0708              2  Chinstrap penguin (Pygoscelis antarctica)  Anvers   
2   PAL0708              3  Chinstrap penguin (Pygoscelis antarctica)  Anvers   
3   PAL0708              4  Chinstrap penguin (Pygoscelis antarctica)  Anvers   
4   PAL0708              5  Chinstrap penguin (Pygoscelis antarctica)  Anvers   

  Island               Stage Individual ID Clutch Completion    Date Egg  \
0  Dream  Adult, 1 Egg Stage         N61A1                No  2007-11-19   
1  Dream  Adult, 1 Egg Stage         N61A2                No  2007-11-19   
2  Dream  Adult, 1 Egg Stage         N62A1               Yes  2007-11-26   
3  Dream  Adult, 1 Egg Stage         N62A2               Yes  2007-11-26   
4  Dream  Adult, 1 Egg Stage         N64A1               Yes  2007-11-21   

   Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  Body Mass (g)  \
0                46.5               17.9                  192           3500   
1                50.0               19.5                  196           3900   
2                51.3               19.2                  193           3650   
3                45.4               18.7                  188           3525   
4                52.7               19.8                  197           3725   

      Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo)  \
0  FEMALE            9.03935          -24.30229   
1    MALE            8.92069          -24.23592   
2    MALE            9.29078          -24.75570   
3  FEMALE            8.64701          -24.62717   
4    MALE            9.00642          -24.61867   

                                Comments  
0  Nest never observed with full clutch.  
1  Nest never observed with full clutch.  
2                                    NaN  
3                                    NaN  
4                                    NaN

In [13]:
# identify the categorical and non categorical columns
cat_cols_df = []
cont_cols_df = []

display("Penguins Data snapshot")
display("rows / columns: ", penguins_adelie_df.shape)
display("information: ", penguins_adelie_df.info())
display("Unique Values")
for i in penguins_adelie_df.columns:
    print("Feature Name: ",i)
    print("Feature DataType: ",penguins_adelie_df[i].dtypes)
    display(penguins_adelie_df[i].unique())
    print("\n")
    if penguins_adelie_df[i].dtypes == 'object':
        cat_cols_df.append(i)
    else:
        cont_cols_df.append(i)
print("categorical columns: ", cat_cols_df)
print("non-categorical columns: ", cont_cols_df)

'Penguins Data snapshot'

'rows / columns: '

(68, 17)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   studyName            68 non-null     object 
 1   Sample Number        68 non-null     int64  
 2   Species              68 non-null     object 
 3   Region               68 non-null     object 
 4   Island               68 non-null     object 
 5   Stage                68 non-null     object 
 6   Individual ID        68 non-null     object 
 7   Clutch Completion    68 non-null     object 
 8   Date Egg             68 non-null     object 
 9   Culmen Length (mm)   68 non-null     float64
 10  Culmen Depth (mm)    68 non-null     float64
 11  Flipper Length (mm)  68 non-null     int64  
 12  Body Mass (g)        68 non-null     int64  
 13  Sex                  68 non-null     object 
 14  Delta 15 N (o/oo)    67 non-null     float64
 15  Delta 13 C (o/oo)    68 non-null     float

'information: '

None

'Unique Values'

Feature Name:  studyName
Feature DataType:  object


array(['PAL0708', 'PAL0809', 'PAL0910'], dtype=object)



Feature Name:  Sample Number
Feature DataType:  int64


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68])



Feature Name:  Species
Feature DataType:  object


array(['Chinstrap penguin (Pygoscelis antarctica)'], dtype=object)



Feature Name:  Region
Feature DataType:  object


array(['Anvers'], dtype=object)



Feature Name:  Island
Feature DataType:  object


array(['Dream'], dtype=object)



Feature Name:  Stage
Feature DataType:  object


array(['Adult, 1 Egg Stage'], dtype=object)



Feature Name:  Individual ID
Feature DataType:  object


array(['N61A1', 'N61A2', 'N62A1', 'N62A2', 'N64A1', 'N64A2', 'N66A1',
       'N66A2', 'N67A1', 'N67A2', 'N68A1', 'N68A2', 'N69A1', 'N69A2',
       'N70A1', 'N70A2', 'N71A1', 'N71A2', 'N72A1', 'N72A2', 'N73A1',
       'N73A2', 'N85A1', 'N85A2', 'N89A1', 'N89A2', 'N63A1', 'N63A2',
       'N65A1', 'N65A2', 'N74A1', 'N74A2', 'N75A1', 'N75A2', 'N86A1',
       'N86A2', 'N87A1', 'N87A2', 'N88A1', 'N88A2', 'N90A1', 'N90A2',
       'N92A1', 'N92A2', 'N93A1', 'N93A2', 'N94A1', 'N94A2', 'N95A1',
       'N95A2', 'N96A1', 'N96A2', 'N98A1', 'N98A2', 'N99A1', 'N99A2',
       'N100A1', 'N100A2'], dtype=object)



Feature Name:  Clutch Completion
Feature DataType:  object


array(['No', 'Yes'], dtype=object)



Feature Name:  Date Egg
Feature DataType:  object


array(['2007-11-19', '2007-11-26', '2007-11-21', '2007-11-28',
       '2007-11-22', '2007-11-30', '2007-12-03', '2008-11-25',
       '2008-11-14', '2008-11-24', '2009-11-17', '2009-11-27',
       '2009-11-23', '2009-11-21', '2009-11-19'], dtype=object)



Feature Name:  Culmen Length (mm)
Feature DataType:  float64


array([46.5, 50. , 51.3, 45.4, 52.7, 45.2, 46.1, 46. , 46.6, 51.7, 47. ,
       52. , 45.9, 50.5, 50.3, 58. , 46.4, 49.2, 42.4, 48.5, 43.2, 50.6,
       46.7, 49.5, 52.8, 40.9, 54.2, 42.5, 51. , 49.7, 47.5, 47.6, 46.9,
       53.5, 49. , 46.2, 50.9, 45.5, 50.8, 50.1, 51.5, 49.8, 48.1, 51.4,
       45.7, 50.7, 52.2, 49.3, 50.2, 45.6, 51.9, 46.8, 55.8, 43.5, 49.6])



Feature Name:  Culmen Depth (mm)
Feature DataType:  float64


array([17.9, 19.5, 19.2, 18.7, 19.8, 17.8, 18.2, 18.9, 19.9, 20.3, 17.3,
       18.1, 17.1, 19.6, 20. , 18.6, 17.5, 16.6, 19.4, 19. , 18.4, 20.8,
       16.7, 18.8, 16.8, 18.3, 20.7, 19.1, 17. , 18.5, 16.4, 19.7, 16.5])



Feature Name:  Flipper Length (mm)
Feature DataType:  int64


array([192, 196, 193, 188, 197, 198, 178, 195, 194, 185, 201, 190, 181,
       191, 187, 200, 205, 203, 199, 210, 212, 202, 206, 189, 207])



Feature Name:  Body Mass (g)
Feature DataType:  int64


array([3500, 3900, 3650, 3525, 3725, 3950, 3250, 3750, 4150, 3700, 3800,
       3775, 4050, 3575, 3300, 3450, 4400, 3600, 3400, 2900, 4550, 3200,
       4300, 3350, 4100, 3850, 4800, 2700, 4500, 3550, 3675, 4450, 3325,
       4000])



Feature Name:  Sex
Feature DataType:  object


array(['FEMALE', 'MALE'], dtype=object)



Feature Name:  Delta 15 N (o/oo)
Feature DataType:  float64


array([ 9.03935,  8.92069,  9.29078,  8.64701,  9.00642,  8.88942,
        8.85664,  8.63701,  8.47173,  8.79581,  8.95063,  8.68747,
        8.72037,  9.0233 ,  9.12277,  9.8059 , 10.02019,  9.14382,
        9.32105,  9.27158,  9.35138,  9.42666,  9.35416,  9.28153,
        9.74144,  9.36799,  8.9399 ,  9.63074,  9.37369,  9.25177,
        9.08458,  9.49283,  9.36668,  9.23196,  9.75486,  9.07825,
        8.83502,  9.43146,  9.80589, 10.02544,  9.53262,  9.61734,
       10.02372,  9.36493,  9.43684,  9.45827,  9.46819,  9.34089,
        9.6895 ,  9.32169,  9.46929,  9.43782,  9.415  ,  9.93727,
        9.56534,  9.77528,  9.62357,  9.88809,  9.74492,  9.46985,
            nan,  9.65061,  9.26715,  9.70465,  9.37608,  9.4618 ,
        9.98044,  9.39305])



Feature Name:  Delta 13 C (o/oo)
Feature DataType:  float64


array([-24.30229, -24.23592, -24.7557 , -24.62717, -24.61867, -24.49433,
       -24.55644, -24.84059, -24.29229, -24.36088, -24.59897, -24.38751,
       -24.80526, -24.38933, -24.90024, -24.7294 , -24.54704, -24.57994,
       -24.64162, -24.64335, -24.6879 , -24.26375, -25.01185, -24.97134,
       -24.59467, -24.47142, -23.89017, -24.34684, -24.52896, -24.69638,
       -24.54903, -24.59996, -24.45195, -24.17282, -24.31198, -25.1455 ,
       -24.65859, -24.6844 , -24.73735, -24.90816, -24.66867, -24.66188,
       -24.86594, -24.66259, -24.16566, -24.35575, -24.45721, -24.45189,
       -24.43062, -24.41562, -24.48403, -24.36202, -24.805  , -24.59066,
       -24.60882, -24.56481, -24.78984, -24.59513, -24.404  , -24.65786,
       -23.78767, -24.48153, -24.31912, -24.53494, -24.40753, -24.70615,
       -24.68741, -24.25255])



Feature Name:  Comments
Feature DataType:  object


array(['Nest never observed with full clutch.', nan,
       'No delta15N data received from lab.'], dtype=object)



categorical columns:  ['studyName', 'Species', 'Region', 'Island', 'Stage', 'Individual ID', 'Clutch Completion', 'Date Egg', 'Sex', 'Comments']
non-categorical columns:  ['Sample Number', 'Culmen Length (mm)', 'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)', 'Delta 15 N (o/oo)', 'Delta 13 C (o/oo)']
